ci go

diff --git a/.cicleci/config.yml b/.cicleci/config.yml
--- a/.cicleci/config.yml
+++ b/.cicleci/config.yml
@@ -1,52 +1,135 @@
-# Javascript Node CircleCI 2.0 configuration file
-#
-# Check https://circleci.com/docs/2.0/language-javascript/ for more details
-#
 version: 2
 jobs:
-  build:
+  checkout_code:
     docker:
-      # specify the version you desire here
       - image: circleci/node:latest
-      
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/mongo:3.4.4
-
     working_directory: ~/circleci-deployment
-
     steps:
       - checkout
       - attach_workspace:
           at: ~/circleci-deployment
-
-      # Download and cache dependencies
       - restore_cache:
           keys:
-          #- v1-dependencies-{{ checksum "package.json" }}
-          # fallback to using the latest cache if no exact match is found
-          #- v1-dependencies-
-          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
-          - yarn-cache-{{ .Branch }}
-          - yarn-cache-
-
+            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
+            - yarn-cache-{{ .Branch }}
+            - yarn-cache-
       - run: yarn install
-
       - save_cache:
-          #key: v1-dependencies-{{ checksum "package.json" }}
           key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
           paths: node_modules
       - persist_to_workspace:
           root: .
           paths: .
-        
-      # run tests!
-      - run: CI=true yarn test
-      #- run: CI=true yarn test:coverage
-      #- run: yarn reportCoverage
-
-      - run: yarn build
-      - run: 
+  check_vulnerabilities:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/circleci-deployment
+    steps:
+      - attach_workspace:
+          at: ~/circleci-deployment
+      - run: yarn install
+      - run: |
+            if [ "${CIRCLE_BRANCH}" == "production" ]; then
+              yarn validate:dependencies
+            else
+              yarn validate:dependencies || true
+            fi
+  test_and_report:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/circleci-deployment
+    steps:
+      - attach_workspace:
+          at: ~/circleci-deployment
+      - run: yarn install
+      - run: CI=true yarn test:coverage
+      - run: yarn reportCoverage
+      - store_artifacts:
+          path: ./coverage/clover.xml
+          prefix: tests
+      - store_artifacts:
+          path: coverage
+          prefix: coverage
+      - store_test_results:
+          path: ./coverage/clover.xml
+  build:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/circleci-deployment
+    steps:
+      - attach_workspace:
+          at: ~/circleci-deployment
+      - run: yarn install
+      - run:
+          name: yarn build
+          command: yarn build
+          # command: |
+          #   if [ "${CIRCLE_BRANCH}" == "production" ]; then
+          #     CI=true PUBLIC_URL=https://circleci-deployment-production.now.sh yarn build
+          #   elif [ "${CIRCLE_BRANCH}" == "development" ]; then
+          #     CI=true PUBLIC_URL=https://circleci-deployment-alpha.now.sh yarn build
+          #   elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+          #     CI=true PUBLIC_URL=https://circleci-deployment-beta.now.sh yarn build
+          #   else
+          #     echo "This failed miserably!"
+          #   fi
+      - persist_to_workspace:
+          root: .
+          paths: .
+  deployment:
+    docker:
+      - image: circleci/node:latest
+    working_directory: ~/circleci-deployment
+    steps:
+      - attach_workspace:
+          at: ~/circleci-deployment
+      - run: yarn install
+      - run: sudo yarn global add now
+      - deploy:
+          # name: Deploy & Alias.
           name: Deploy Master to Firebase
           command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_DEPLOY_TOKEN"
+          # command: |
+          #   if [ "${CIRCLE_BRANCH}" == "production" ]; then
+          #     now build -t ${NOW_TOKEN} -n=circleci-deployment --static
+          #     now -t ${NOW_TOKEN} alias circleci-deployment-production.now.sh
+          #   elif [ "${CIRCLE_BRANCH}" == "development" ]; then
+          #     now build -t ${NOW_TOKEN} -n=circleci-deployment --static
+          #     now -t ${NOW_TOKEN} alias circleci-deployment-alpha.now.sh
+          #   elif [ "${CIRCLE_BRANCH}" == "master" ]; then
+          #     now build -t ${NOW_TOKEN} -n=circleci-deployment --static
+          #     now -t ${NOW_TOKEN} alias circleci-deployment-beta.now.sh
+          #   else
+          #     echo "This failed miserably!"
+          #   fi
+workflows:
+  version: 2
+  test_build_deploy:
+    jobs:
+      - checkout_code
+      - check_vulnerabilities:
+          requires:
+            - checkout_code
+      - test_and_report:
+          requires:
+            - checkout_code
+      - build:
+          requires:
+            - checkout_code
+          filters:
+            branches:
+              only:
+                - development
+                - master
+                - production
+      - deployment:
+          requires:
+            - check_vulnerabilities
+            - test_and_report
+            - build
+          filters:
+            branches:
+              only:
+                - development
+                - master
+                - production
